version: '3.8'

services:
  # rename?
  app:
    build: .
    depends_on:
      - elasticsearch6
      - elasticsearch7
      - mysql
      - redis
    command: bin/rails server --binding 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      - DB_HOST=mysql
      - ES_A_HOST=http://elasticsearch6:9200
      - ES_B_HOST=http://elasticsearch7:9200
      - REDIS_HOST=redis


  # TODO: COPY SECRETS
  # TODO: update ports in readme

  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms750m -Xmx750m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_6_data:/usr/share/elasticsearch6/data
    ports:
      - 9268:9200

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms750m -Xmx750m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch7/data
    ports:
      - 9277:9200

  kibana6:
    image: docker.elastic.co/kibana/kibana:6.8.9
    depends_on:
      - elasticsearch6
    ports:
      - 5668:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch6:9200

  mysql:
    image: mysql:5.6
    volumes:
      - ./docker/my.cnf:/etc/my.cnf
      - db_data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379

  resque-web:
    command: 'bundle exec resque-web ./lib/setup_resque.rb -F -r redis:6379'
    build: .
    depends_on:
      - redis
    ports:
      - '5678:5678'

  resque-workers:
    command: 'bundle exec rake environment resque:work'
    build: .
    depends_on:
      - elasticsearch6
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - ES_A_HOST=http://elasticsearch6:9200
      - REDIS_HOST=redis
      - QUEUE=*
      - VERBOSE=true

  resque-scheduler:
    command: 'bundle exec rake resque:scheduler'
    build: .
    depends_on:
      - elasticsearch6
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - ES_A_HOST=http://elasticsearch6:9200
      - REDIS_HOST=redis
      - QUEUE=*
      - VERBOSE=true

volumes:
  db_data:
  es_6_data:
  es_7_data:
  gem_cache:
